SELECT  
	(SELECT CONCAT(CONCAT(fsp.FNAME, ' '), fsp.LNAME) 
		FROM F21_S001_22_PATIENT fsp 
		WHERE fsp.PATIENT_ID=fst3.PATIENT_ID) AS patid,
	SUM(fspp.PAT_AMOUNT + fspp.INS_AMOUNT) AS patamount 
FROM F21_S001_22_PAYMENT_PLAN fspp 
	INNER JOIN F21_S001_22_TREATMENT fst3 ON fspp.TX_ID = fspp.TX_ID 
WHERE fspp.TX_ID IN (
SELECT fst.TX_ID 
FROM F21_S001_22_TREATMENT fst 
WHERE fst.DATETIME > SYSDATE - #DAYSVAL#
	AND fst.OPERATORY_ID IN (SELECT fso.OPERATORY_ID 
		FROM F21_S001_22_OPERATORY fso 
		WHERE fso.OP_TYPE = '#OPERATORYTYPE#')
) GROUP BY fst3.PATIENT_ID